# Generated by Django 3.2.6 on 2022-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
